import Head from 'next/head'

/** Style-sheet **/
import styled from 'styled-components'

/*
	These are default styles you can over-ride them according to need of your project.
*/

// Whole-Boby-Container
const Container = styled.div`
	min-height: 100vh;
	padding: 0 0.5rem;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	height: 100vh;
`

// Main-Wapper
const MainWapper = styled.div`
	padding: 5rem 0;
	flex: 1;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;

	.title {
		margin: 0;
		line-height: 1.15;
		font-size: 4rem;

		a {
			color: #0070f3;
			text-decoration: none;
		}
	}
`

export default function Home() {
	return (
		<Container>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<MainWapper>
				<h1 className="title">
					Welcome to <a href="#">Next.js!</a>
				</h1>
			</MainWapper>
		</Container>
	)
}
